### ISSUE TITLE
How to add seed ?

### ISSUE THREAD

**Issue by On9Ora** [dreamscached/vanitygen-colab#3]
I tried -s but couldn't execute successfully

**Comment by dreamscached** [comment]
What exactly is the problem? I have just tried it myself and it seems like it picks it up as expected.

When you create a file in default file view (not navigating up to /) it's accessible in /content, try specifying absolute path like /content/foobar

![obrazek](https://user-images.githubusercontent.com/74068927/202493372-eb1910f8-9c19-49fc-b398-8db4b398d8d8.png)
![obrazek](https://user-images.githubusercontent.com/74068927/202494079-37b9c4d4-40ab-4415-9f06-eda8e6c088d3.png)

**Comment by On9Ora** [comment]
[image: image.png]

Herman S. ***@***.***> 於 2022年11月17日 週四 晚上11:50寫道：

**Comment by On9Ora** [comment]
And I can't find this file... Also, what should I do if I want to find
ETH, thank you for teaching me


‪‫זהריאל‬‎ ***@***.***> 於 2022年11月18日 週五 凌晨3:38寫道：‬

**Comment by dreamscached** [comment]
I can't see what you're attaching, reply to this issue on GitHub not via e-mail, please.

> Also, what should I do if I want to find ETH, thank you for teaching me

Use coin switch in the options list.

**Comment by dreamscached** [comment]
Closing as stale, no more info on this issue was received.
