### ISSUE TITLE
Usage of this notebook may lead to (reversible) account ban on Google Colab

### ISSUE THREAD

**Issue by AndrewSingleplayer** [dreamscached/vanitygen-colab#4]
Your colab account will be permanently banned.

**Comment by dreamscached** [comment]
You can submit appeal and they will unban you. Also this is a crypto related software, and they have it in their ToS that they do not condone using their services for mining crypto, this might be detected as an alike operation.

For the reason said above it's not crypto mining so they *will* most likely unban, I've been there before.

**Comment by dreamscached** [comment]
I'll leave it a pinned issue however, since this is obviously something people need to keep in mind.

**Comment by AndrewSingleplayer** [comment]
ok, but the final .txt file where it is stored?

**Comment by dreamscached** [comment]
It's wherever you save it, try searching in /content.

**Comment by AndrewSingleplayer** [comment]
I am still getting banned after 2 minutes, unbanned after 2 days then banned again...

**Comment by dreamscached** [comment]
That's unfortunate but that's Google's policy of preventing abuse of their services for mining crypto. While this software doesn't do any of it, it does still perform a lot of crypto-related stuff which most likely triggers the automatic detection. Sorry, I cannot help that.

**Comment by OmiChrome** [comment]
what is exactly i have to put in appeal to get unbaned? @dreamscached  
i was trying to crack passsword , but end up banned

**Comment by dreamscached** [comment]
Simply something along the lines of

> the software I'm using isn't anything related to mining cryptocurrencies and doesn't fall under ToS violation

About cracking a password though I don't know if they will really unban you if you tell them the exact reason why you were using vanitygen

**Comment by OmiChrome** [comment]
i wasn't using vanitygen ,  i was using hashcat 
 i searched for colab-ban i got your issuue linked , show i asked here

**Comment by dreamscached** [comment]
I haven't used hashcat/jtr on Colab myself, at least not in the recent year or two, so I unfortunately don't know what you can do about it. I'm unsure if this is allowed on Colab.
