### ISSUE TITLE
now it seems not working

### ISSUE THREAD

**Issue by asuka431** [dreamscached/vanitygen-colab#5]
/content/linux-binary
/content
popd -> /content
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-32-beeb053a806c>](https://localhost:8080/#) in <module>
      6   get_ipython().run_line_magic('pushd', '"linux-binary"')
      7   from shlex import quote
----> 8   cli = " ".join(map(quote, param))
      9   get_ipython().system('$cli')
     10 finally:

[/usr/lib/python3.8/shlex.py](https://localhost:8080/#) in quote(s)
    323     if not s:
    324         return "''"
--> 325     if _find_unsafe(s) is None:
    326         return s
    327 

TypeError: expected string or bytes-like object

**Comment by dreamscached** [comment]
Can you give an example of your inputs? I couldn't reproduce it.

**Comment by asuka431** [comment]
https://colab.research.google.com/github/dreamscached/vanitygen-colab/blob/b944a94cf1277b114332fdd8f4af71bec81f2fb8/VanityGen.ipynb#scrollTo=FPxAZ60tOFHh
this works.
so may be spiliting prosess has problem? (skips compile, i think.)

**Comment by dreamscached** [comment]
That's why I'm asking for your inputs, I need them to figure what is being processed wrong. If they have sensitive info feel free to omit it.

Edit: nevermind, I found the culprit of it.

**Comment by dreamscached** [comment]
Should be fixed now.
